version: "3.5"

volumes:
    db:
    mangosd_etc:
    realmd_etc:

services:
    db:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        image: mangosbot-db
        networks:
            backend:
                aliases:
                - database     
        ports:
            - "127.0.0.1:3306:3306" # Local SQL
        volumes:
            - db:/var/lib/mysql
            #- ./db/init:/docker-entrypoint-initdb.d:ro
        restart: "unless-stopped"
        environment:
            - TZ=Europe/London
            - MYSQL_ROOT_PASSWORD=mangos

    mangosd:
        build:
            context: .
            dockerfile: ./mangosd/Dockerfile
        image: mangosbot-mangosd
        depends_on:
            - db  
        networks:
            - backend
        ports:
            - "8085:8085"
            - "127.0.0.1:3443:3443" # Remote Console
            #- 7878:7878 # Enable if you want to use SOAP   
        volumes:
            - "./config:/opt/cmangos/etc"
            - "./logs:/opt/cmangos/logs"
            - "./data:/opt/cmangos/data"
            - "./scripts:/opt/cmangos/scripts"
            - "./backup:/opt/cmangos/backup"
            - "./sql:/opt/cmangos/sql"
            - "./bin:/opt/cmangos/bin"
            - "/etc/localtime:/etc/localtime:ro"
        restart: "unless-stopped"
        stop_grace_period: 15m # The amount of seconds to wait before killing the container forcefully (if the server has a lot of bots is recommended to increase this)
        environment:
            - TZ=Europe/London
            - CHARACTERS_DB=classiccharacters
            - MANGOSD_DB=classicmangos
            - REALMD_DB=classicrealmd
            - PLAYERBOTS_DB=classicplayerbots
            - DB_USER=mangos
            - DB_PASS=mangos
            - DB_PORT=3306
            - REALMD_USER=mangos
            - REALMD_PASS=mangos
            - DB_SERVER=database
            - REALMD_SERVER=database
        security_opt:
          - seccomp:unconfined
        cap_add:
          - SYS_PTRACE

    realmd:
        build:
            context: .
            dockerfile: ./realmd/Dockerfile
        image: mangosbot-realmd
        depends_on:
            - db
        networks:
            - backend
        ports:
            - "3724:3724"
        volumes:
            - "./config:/opt/cmangos/etc"
            - "./logs:/opt/cmangos/logs"
            - "./bin:/opt/cmangos/bin"
            - "/etc/localtime:/etc/localtime:ro"
        restart: "unless-stopped"
        environment:
            - TZ=Europe/London
            - REALMD_DB=classicrealmd
            - DB_USER=mangos
            - DB_PASS=mangos
            - DB_SERVER=database
            - DB_PORT=3306

networks:
    backend:
        name: mangosbot_backend